"""initial migration

Revision ID: 6c8993d5b82b
Revises: None
Create Date: 2016-10-15 17:15:09.287000

"""

# revision identifiers, used by Alembic.
revision = '6c8993d5b82b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
